### PR TITLE
move timeago to dependencies reg

### PR DESCRIPTION
**Pull request by mehmetkose**
It was not installing timeago.js.

### CODE REVIEW

**Comment by dzhurley** [comment]
@mehmetkose thanks for this!

**Comment by mehmetkose** [comment]
sure! also there is some problem with current version of timeago.js, but @2.0.3 works..

**Comment by dzhurley** [comment]
@mehmetkose what sort of problem is it?

**Comment by mehmetkose** [comment]
time was not changing in realtime. and there was a error log in the console. but unfortunately I cant find it now. I have installed exact 2.0.3 version to fix-it

**Comment by dzhurley** [comment]
gotcha, i can look into that sometime soon as well.

**Pull request merged**
